"""update

Revision ID: 12bc0bdfa44a
Revises: 5137fb463a5c
Create Date: 2019-01-23 22:57:57.982978

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12bc0bdfa44a'
down_revision = '5137fb463a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dummy_model', sa.Column('dummy_active', sa.Boolean(), nullable=True))
    op.alter_column('dummy_model', 'float_zahl',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('dummy_model', 'int_zahl',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dummy_model', 'string',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dummy_model', 'string',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('dummy_model', 'int_zahl',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dummy_model', 'float_zahl',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('dummy_model', 'dummy_active')
    # ### end Alembic commands ###
