"""update

Revision ID: 4af67fb48e16
Revises: 12bc0bdfa44a
Create Date: 2019-01-24 18:12:44.439418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af67fb48e16'
down_revision = '12bc0bdfa44a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dummy_model', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dummy_model', 'created')
    # ### end Alembic commands ###
