"""update

Revision ID: 5137fb463a5c
Revises: ff7f02c8a96e
Create Date: 2019-01-12 17:05:53.831912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5137fb463a5c'
down_revision = 'ff7f02c8a96e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dummy_model', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dummy_model', 'user_id')
    # ### end Alembic commands ###
