"""update

Revision ID: ff7f02c8a96e
Revises: 
Create Date: 2019-01-10 19:51:02.912748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff7f02c8a96e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dummy_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string', sa.String(length=80), nullable=True),
    sa.Column('int_zahl', sa.Integer(), nullable=True),
    sa.Column('float_zahl', sa.Float(), nullable=True),
    sa.Column('bool', sa.Boolean(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dummy_model')
    # ### end Alembic commands ###
